name: Open-CE Feedstock PR Tests

on:
  pull_request:
    branches: [main]

jobs:
  optional_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: "3.7"
      - uses: cdeepali/open-ce/.github/actions/feedstock-optional-pr@dc-check-recipes
  required_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: "3.7"
      - uses: cdeepali/open-ce/.github/actions/feedstock-required-pr@dc-check-recipes
